-- AlterTable
ALTER TABLE "UserUsage" ADD COLUMN     "giftCardsSent" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "greetingCardsSent" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "imageAnalyses" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "lettersSentStandard" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "postcardsSent" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "totalSpent" DECIMAL(10,2) NOT NULL DEFAULT 0,
ADD COLUMN     "voiceTranscriptions" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "windowlessLettersSent" INTEGER NOT NULL DEFAULT 0,
ALTER COLUMN "resetAt" DROP DEFAULT;
