-- AlterTable
ALTER TABLE "UserUsage" ADD COLUMN IF NOT EXISTS "postcardsSent" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "UserUsage" ADD COLUMN IF NOT EXISTS "lettersSentStandard" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "UserUsage" ADD COLUMN IF NOT EXISTS "greetingCardsSent" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "UserUsage" ADD COLUMN IF NOT EXISTS "windowlessLettersSent" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "UserUsage" ADD COLUMN IF NOT EXISTS "giftCardsSent" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "UserUsage" ADD COLUMN IF NOT EXISTS "totalSpent" DECIMAL(10,2) NOT NULL DEFAULT 0;
